// Quote math, ported from `programs/rotator/src/math.rs`.
//
// This must agree with the on-chain implementation EXACTLY. The front end shows
// a trader what they will receive before they sign; if this disagrees by even
// one unit the trade either fails on the slippage guard or fills at a number
// the user did not expect, and nothing throws. `test/quote.test.ts` checks every
// function here against vectors generated by the Rust code itself.
//
// `null` means "the pool will reject this trade", not "zero".
export const SCALE = 1n << 64n;
const U128_MAX = (1n << 128n) - 1n;
const U64_MAX = (1n << 64n) - 1n;
/** `a * b / d`, mirroring the Rust checked arithmetic (null where it overflows u128). */
export function mulDiv(a, b, d) {
    if (d === 0n)
        return null;
    const q = a / d;
    const r = a % d;
    const qb = q * b;
    if (qb > U128_MAX)
        return null;
    const rb = r * b;
    if (rb > U128_MAX)
        return null;
    const res = qb + rb / d;
    if (res > U128_MAX)
        return null;
    return res;
}
/** Effective X reserve: `Rx / I`. Higher index -> smaller reserve -> higher price. */
export function effectiveX(reserveX, indexQ) {
    if (indexQ === 0n)
        return null;
    return mulDiv(reserveX, SCALE, indexQ);
}
function netAfterFee(amount, feeBps) {
    if (feeBps >= 10_000)
        return null;
    return (amount * (10000n - BigInt(feeBps))) / 10000n;
}
/**
 * X received for `lamportsIn`.
 *
 * Returns null when the quote reaches the reserve. That is not a rounding
 * guard: when the tracked stock is down (I < 1) the effective reserve exceeds
 * the X actually held, so the curve will quote more X than exists. The pool
 * rejects rather than filling short, so the UI must surface "size down", not
 * silently clamp.
 */
export function buyX(reserveX, reserveQ, indexQ, lamportsIn, feeBps) {
    if (lamportsIn === 0n)
        return 0n;
    const ex = effectiveX(reserveX, indexQ);
    if (ex === null)
        return null;
    const net = netAfterFee(lamportsIn, feeBps);
    if (net === null)
        return null;
    if (net === 0n)
        return 0n;
    const denom = reserveQ + net;
    if (denom > U128_MAX)
        return null;
    const dx = mulDiv(ex, net, denom);
    if (dx === null)
        return null;
    if (dx >= reserveX)
        return null;
    if (dx > U64_MAX)
        return null;
    return dx;
}
/** Lamports received for `xIn`. Bounded by the reserve by construction. */
export function sellX(reserveX, reserveQ, indexQ, xIn, feeBps) {
    if (xIn === 0n)
        return 0n;
    const ex = effectiveX(reserveX, indexQ);
    if (ex === null)
        return null;
    const net = netAfterFee(xIn, feeBps);
    if (net === null)
        return null;
    if (net === 0n)
        return 0n;
    const denom = ex + net;
    if (denom > U128_MAX)
        return null;
    const dq = mulDiv(reserveQ, net, denom);
    if (dq === null)
        return null;
    const capped = dq < reserveQ ? dq : reserveQ;
    if (capped > U64_MAX)
        return null;
    return capped;
}
/** Which stock slot is paired right now. Pure function of the clock. */
export function activeSlot(nowTs, startTs, rotateSecs, n) {
    if (n === 0 || rotateSecs <= 0n)
        return 0;
    let elapsed = nowTs - startTs;
    if (elapsed < 0n)
        elapsed = 0n;
    return Number((elapsed / rotateSecs) % BigInt(n));
}
